spring.application.name=quote-remittance-backend

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/remittance
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Webhook Security Secret
remittance.webhook.secret=whsec_super_secret_bouncers_password_12345
quote.expiry-minutes=15
quote.fee-percentage=0.015
