# application-prod.properties

server.port=${PORT:8080}

# Production DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Production logging
spring.jpa.show-sql=false
logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

# Production error handling
server.error.include-stacktrace=never
server.error.include-message=never

# HTTPS / Render proxy support
server.forward-headers-strategy=framework
