# Production Server
server.port=${PORT:8080}

# Production Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Production JPA
spring.jpa.show-sql=false

# Security
server.error.include-stacktrace=never
server.error.include-message=never

# Production CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

# HTTPS / Proxy Support (important on Render)
server.forward-headers-strategy=framework
