# Production Server
server.port=${PORT:8080}

# Production Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Production Security
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
jwt.secret=${JWT_SECRET}

# Production JPA
spring.jpa.show-sql=false

# Production Error Handling
server.error.include-stacktrace=never
server.error.include-message=never

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

# HTTPS / Proxy Support
server.forward-headers-strategy=framework
