name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: remittance
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Grant Execute Permission
        run: chmod +x mvnw

      - name: Run Tests
        run: ./mvnw test
        env:
            PAYSTACK_API_SECRET: ${{secrets.PAYSTACK_API_SECRET}}
            REMMITTANCE_WEBHOOK_SECRET: ${{secrets.REMMITANCE_WEBHOOK_SECRET}}

      - name: Build Application
        run: ./mvnw clean package -DskipTests
        env:
          PAYSTACK_API_SECRET: ${{secrets.PAYSTACK_API_SECRET}}
          REMMITTANCE_WEBHOOK_SECRET: ${{secrets.REMMITANCE_WEBHOOK_SECRET}}
